# yaml 配置
version: '3'
services:
  docker-terminal:
    build: 
      context: .
      dockerfile: Dockerfile
    image: docker-terminal
    container_name: docker-terminal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
